### PR TITLE
Create translation-menu.sh

### PR DESCRIPTION
**Pull request by ghost**
Program for easy use of the translate-shell project

### CODE REVIEW

**Comment by soimort** [comment]
Thanks for the PR!

I'm not going to maintain third-party scripts here, though -- please feel free to keep it in your own project as long as it's useful to others.

**Comment by jeanrafaellourenco** [comment]
Thanks for the answer. Could you tell me what you thought about the implementation?

**Comment by soimort** [comment]
I think it's fine if it fits your own specific needs -- Assuming you're a Debian/Ubuntu user and a Portuguese speaker. Can't comment on your code itself, but if you're ever going to start an open-source project like this, think about users -- better not to make any assumptions who they are, which distros they prefer or what languages they speak. Generalization is important.

And since this program just invokes `trans`, and does not contain actual source code from it, you don't have to put "@soimort" in the Author field: )

**Comment by ghost** [comment]
Thank you! Please delete this pr, I intend to recreate my idea following your advice.

**Pull request closed without merging**
