### PR TITLE
Add DeepL Translator (close #203)

### LINKED ISSUE #203: [Feature request]: add support for DeepL translator
It doesn't support many languages and seems API's undocumented but it does a hell of a job in translating less conventional stuff. Just leaving the request her and to say thank you for a super useful tool  =)

https://www.deepl.com/translator
https://github.com/vsetka/deepl-translator

### PR DESCRIPTION
**Pull request by soimort**
Due to recurring requests (#203, [#121](https://github.com/soimort/translate-shell/issues/121#issuecomment-325920874), and some email buried in the snow).

Usage:
1. (One-time) Call `trans` with option `-e deepl`.
2. (Permanent) Add `:engine          "deepl"` to the [configuration](https://github.com/soimort/translate-shell/wiki/Configuration) file.

Example:
```sh
$ trans :en 'mi casa es su casa' -e deepl
mi casa es su casa

my home is your home

[ Español → English ]

    My house is your house.
    My home is your home.
    my house is your house
```

### CODE REVIEW

**Comment by tflo** [comment]
There seems to be an encoding problem with DeepL (at least on my Mac). It returns non-ASCII characters with their Unicode code point. Example:

```
$ trans -b -e deepl :de+fr+es 'Listen to me!'
H\u00f6r mir zu!
\u00c9coute-moi bien!
\u00a1Esc\u00fachame!
```

The replaced characters here are `ö`, `É`, `¡` and `ú`.

This is only with the _deepl_ engine. _google_, _bing_ and _yandex_ are fine.

– Tom

**Comment by soimort** [comment]
@tflo 
This is an existing issue on macOS / *BSD, since non-GNU systems do not have anything [equivalent to GNU `printf`](https://github.com/soimort/translate-shell/commit/0cc2211afd390e0370bc961e376f9d86c8e31764#diff-eb89885bee76ed3da732494abdbf1bf9R179) that properly prints Unicode-escaped string to stdout.

**Comment by tflo** [comment]
Thanks for the info. Will try to find a workaround…

– Tom

**Comment by tflo** [comment]
@soimort 

Well, here an – ugly – workaround, with a bit of Perl to convert the characters:

```
$ trans -b -e deepl :de+fr+es 'Listen to me!' | perl -Mopen=':std',':encoding(UTF-8)' -pe '$_ =~ s/\\u(.{4})/chr(hex($1))/eg;'
Hör mir zu!
Écoute-moi bien!
¡Escúchame!
```
Tested only on a few samples.

– Tom

**Comment by soimort** [comment]
Should be fixed by 4536adcf5d2aed1d7f1984c204a7fbc6f0bc3f0a using bash.

**Comment by vmeade** [comment]
Preface: Sorry I am noob.

I 'git pull' in my local 'translate-shell' directory for the newest files (to include DeepL) however in the command line "trans -S" deepl is not found. Could you steer me in a direction to solving this problem?

**Comment by soimort** [comment]
@vmeade Please check your version. Updated one should be 0.9.6.6.

```
$ trans -V          
Translate Shell       0.9.6.6

platform              Linux
gawk (GNU Awk)        4.2.0
fribidi (GNU FriBidi) 0.19.7
audio player          mplayer
terminal pager        less
terminal type         xterm
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 happiness.trans
init file             /home/soimort/.translate-shell/init.trans

Report bugs to:       https://github.com/soimort/translate-shell/issues
```

**Comment by tflo** [comment]
> Should be fixed by 4536adc using bash.

Isn’t this committed yet?

With DeepL and 0.9.6.6 I still get the hex code points in the output when I remove my perl after-treatment. The same with 0.9.6.6-git:c8107fe (installed via Homebrew `--HEAD`).

**Comment by waxfingers** [comment]
Seems broken again in 0.9.6.7 (via homebrew)

**Pull request merged**
