### PR TITLE
use https in URLs, Apertium, Google, Yandex

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by soimort** [comment]
Unfortunately, HTTPS won't work that way. You'll still need an actual SSL/TLS implementation... (which gawk doesn't have)

**Comment by vszakats** [comment]
Oh, so that's the reason, thanks for your quick feedback! Maybe calling out to `curl` could help to use SSL/TLS. Anyhow, closing this for now.

**Comment by vszakats** [comment]
The two URL updates in `include/Languages.awk`, may still be useful.

**Comment by soimort** [comment]
> The two URL updates in include/Languages.awk, may still be useful.

Yes, they're. I'll update all such links to HTTPS when applicable at a later time.

Thanks for the PR, anyway!

**Comment by vszakats** [comment]
Thank you @soimort!

**Comment by requiredregistration** [comment]
@soimort 4 years have passed, can you do it now?

**Pull request closed without merging**
